CmNode memory fix
KristopherGBaker/Maaku pull request #29
Opened 2019-04-27 03:42 UTC by NightFlyer

Here's the fix for the problem I mentioned in the pull request #28 which just added a test to show that the memory problem existed.

This code changes the cmarkNode memory handling so that it relies on Swift's reference counting rather than trying to keep track of who should free the memory. This doesn't add to the memory footprint, since it really just involves keeping the CMNode associated with the document alive as long as anyone is referencing any CMNodes in that document -- and as was shown by the test in pull request #28, that had to happen anyway, otherwise your program would crash.

Each CMNode has a minor size increase (I replaced a Bool with a reference), but I don't think that minor size change will cause a problem for most users.

2019-04-27 06:27 UTC, KristopherGBaker approved these changes

2019-04-27 06:29 UTC, KristopherGBaker requested changes
There's a conflict after merging the previous PR

2019-04-27 18:24 UTC, NightFlyer commented
Merged in latest and added another memory test.

2019-04-28 00:33 UTC, KristopherGBaker approved these changes

2019-04-28 00:36 UTC, merged